# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - https://raw.githubusercontent.com/WinterChenS/imgrpo/master/mp3/%E6%96%B0%E8%A3%A4%E5%AD%90-%E7%94%9F%E6%B4%BB%E5%9B%A0%E4%BD%A0%E8%80%8C%E7%81%AB%E7%83%AD.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: https://raw.githubusercontent.com/WinterChenS/imgrpo/develop/blog/20200321174412.jpg

# 默认文章封面图（随机调用,支持外链）
#cover: 
 # - https://raw.githubusercontent.com/WinterChenS/imgrpo/develop/blog/20200321174412.jpg

 
# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    github: https://github.com/WinterChenS
    wechat: http://img.winterchen.com/Wechat.jpg
    email: mailto:winterchen001@gmail.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: true
    # 备案号
    beianInfo: 浙ICP备17056942号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '77f2adc33e0112d086d7'
    # 应用秘钥
    clientSecret: 'e926aa3a621556609b2c2b76d89320fa524e23cd'
    # issue仓库名
    repo: 'WinterChenS.github.io'
    # Github名
    owner: 'WinterChenS'
    # Github名
    admin: ['WinterChenS']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false
    # 是否启用快捷键提交评论(cmd|ctrl + enter)
    enableHotKey: true
    # 如果当前页面没有相应的 isssue 且登录的用户属于 admin，则会自动创建 issue。如果设置为 true，则显示一个初始化页面，创建 issue 需要点击 init 按钮
    createIssueManually: true

# 网站关键字
keywords: Luis

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: G-30C04D6TMS

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml